SET GLOBAL event_scheduler = ON;

CREATE EVENT genera
ON SCHEDULE EVERY 5 MINUTE STARTS NOW()
DO
INSERT INTO ELEMSCANNER (INCREMENTO,NOMEE,NOMEL,VALORE,DATA_SCAN)
SELECT CONTA, NOME, NOMELOCATION, RAND(), DATE_FORMAT(NOW(), '%Y-%m-%d')
FROM CONTEGGIO, ELEMENTO,CAPOLUOGO;


CREATE EVENT incrementa
ON SCHEDULE EVERY 5 MINUTE STARTS NOW()
DO
UPDATE CONTEGGIO SET CONTA = CONTA + 1;
